name: Build docs

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          dockerfile: Dockerfile
          path: .
          username: jamct
          password: ${{ secrets.GITHUB_TOKEN }}
          repository: jamct/demo-docs/mkdocs
          registry: docker.pkg.github.com
          tags: latest
