site_name: Test-Doku
dev_addr: "0.0.0.0:8080"
site_author: "Ihr Name"
theme: "flatly"

markdown_extensions:
    - attr_list
    - admonition
    - fontawesome_markdown
    
nav:
    - Willkommen: index.md
    - Test: test.md
